### PR TITLE
Fix building Swish 2.0 for Xcode 9.3

### LINKED ISSUE #118: Errors on 2.0.3 with Xcode 9.3
One of my projects is using Swish 2.0.3. I updated Xcode to 9.3 and I started to see a couple errors. It would be great to get a quick fix for Swish 2.0 out if possible. Unfortunately, we're not able to migrate to Swish 3.0 at this time. Here are the errors I'm seeing:
```
Swish/Source/Models/APIClient.swift:10:108: Struct 'JSONDeserializer' is internal and cannot be referenced from a default argument value
```
(can't use internal type in default arg)

and
```
Swish/Source/Protocols/Request.swift:29:21: Missing argument for parameter #1 in call
```
(needs another`()` inside `.success()`)

I've forked and branched from what looked like a good point for 2.0: 4c9233c. I don't want to open a PR onto master here -- is there a good branch I could PR with these updates? My changes are here:
https://github.com/gstro/Swish/tree/2.0-fixes . Could there be a 2.x release branch? Would love to have this updated on CocoaPods soon too.

### PR DESCRIPTION
**Pull request by gfontenot**
Xcode 9.3 brings along Swift 3.3, which has a couple _slightly_ different
behaviors that need to be special cased. Our current release (3.0+) of Swish
handles these changes already, but some users are unable to upgrade right now,
and we shouldn't make their lives more difficult.

This adds the fixes for Swift 3.3 without breaking compatibility for Swift 3.2
users.

I'm opening this PR for visibility but I'm going to delete the 2.0.3 branch as soon as I have a 2.0.3 release tagged.

Fixes #118

### CODE REVIEW

File: Source/Models/JSONDeserializer.swift [hunk 1]
```diff
@@ -1,15 +1,17 @@
 import Argo
 import Result
 
-struct JSONDeserializer: Deserializer {
-  func deserialize(_ data: Data?) -> Result<Any, SwishError> {
+public struct JSONDeserializer: Deserializer {
```
Comment (sharplet) [inline Source/Models/JSONDeserializer.swift:4]: Huh. Was this never public before?

File: Source/Protocols/Request.swift [hunk 2]
```diff
@@ -26,6 +26,10 @@ public extension Request where ResponseObject: Collection, ResponseObject.Iterat
 
 public extension Request where ResponseObject == EmptyResponse {
   func parse(_ j: JSON) -> Result<ResponseObject, SwishError> {
+    #if swift(>=3.3)
```
Comment (sharplet) [inline Source/Protocols/Request.swift]: How do you feel about outdenting these?

**Review by sharplet — APPROVED** [review]
Minor comments, but lgtm 👍

File: Source/Models/JSONDeserializer.swift (hunk 1 above)
Comment (gfontenot) [reply Source/Models/JSONDeserializer.swift:4]: It never needed to be! I was actually a little surprised too.

File: Source/Protocols/Request.swift (hunk 2 above)
Comment (gfontenot) [reply Source/Protocols/Request.swift]: do you mean like

```swift
func parse() {
  #if swift(>=3.3)
    return .success(())
  #else
    return .success()
  #endif
}
```
?

Comment (gfontenot) [reply Source/Protocols/Request.swift]: I'm fine with it, just want to make sure we're on the same page wrt style.

Comment (sharplet) [reply Source/Protocols/Request.swift]: Oh I suppose I meant the C style, outdenting to the left edge:

```swift
  func parse() {
#if swift(>=3.3)
    return .success(())
#else
    return .success()
#endif
  }
```

Comment (gfontenot) [reply Source/Protocols/Request.swift]: That looks... real bad to me tbh. How do you feel about the way I just indented the file?

Comment (gfontenot) [reply Source/Protocols/Request.swift]: also this is the most bandaid-y of bandaid-y code so we probably don't need to go too deep into this here bikeshed.

Comment (sharplet) [reply Source/Protocols/Request.swift]: I'm not too fussed, so feel free to use whichever style you prefer. I think I tend to go for that style to minimise diff noise when the conditionals are eventually removed.

Comment (gfontenot) [reply Source/Protocols/Request.swift]: yep, I hear you. This is a dead-end refactor though, these changes are never even making it to master. I'm going to go ahead and merge this as is currently written.
